services:
  backend:
    build:
      args:
      - NODE_ENV=development
      context: backend
      target: dev-envs
    command: npm run start
    environment:
      - NODE_ENV=development
    ports:
      - 80:80
      - 9229:9229
      - 9230:9230
    secrets:
      - db-password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public
      - private
  frontend:
    build:
      context: frontend
      target: dev-envs
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public
    depends_on:
      - backend
networks:
  public:
  private:
volumes:
  back-notused:
